using NuGet.DependencyResolver;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace HospitalManagementServer.Models
{
    public class Patient
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)] // Specify that the value will not be auto-generated by the database
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }


        public  string? Age { get; set; }   





        public ICollection<DoctorPatient> DoctorPatients { get; set; }

        public List<Doctor> Doctors { get; set; }

        public Patient()
        {
            DoctorPatients = new List<DoctorPatient>();

            Doctors = new List<Doctor>();
        }
    }
}
